<a href="https://colab.research.google.com/github/LakshyaPalCoder20119/Data_Science_ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr.ndim)
    

In [16]:
arr.dtype

dtype('int64')

In [17]:
arr = np.array([1,2,3,4,5,6.6])

In [18]:
arr.dtype

dtype('float64')

In [4]:
lst = [1]*10000
     

In [19]:
print(lst)
print(len(lst))
print(type(lst))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [20]:
arr = np.ones(10000,dtype="uint8")
     

In [21]:
print(arr)

[1 1 1 ... 1 1 1]


In [22]:
%timeit sum(lst)

71.2 µs ± 945 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [23]:
%timeit arr.sum()

13.4 µs ± 160 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [24]:
%timeit sum(arr)

1.55 ms ± 22.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [25]:
arr = np.ones((3,4),dtype="uint8")
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [26]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [27]:
arr= np.arange(5,25,2)
print(arr)

[ 5  7  9 11 13 15 17 19 21 23]


In [28]:
arr[2:5]

array([ 9, 11, 13])